<?php

namespace DoctrineProxies\__CG__\configuration_process;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class form extends \configuration_process\form implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chance' => [parent::class, 'chance', null],
        "\0".parent::class."\0".'close' => [parent::class, 'close', null],
        "\0".parent::class."\0".'connection_form' => [parent::class, 'connection_form', null],
        "\0".parent::class."\0".'created_by' => [parent::class, 'created_by', null],
        "\0".parent::class."\0".'date_created' => [parent::class, 'date_created', null],
        "\0".parent::class."\0".'date_effective' => [parent::class, 'date_effective', null],
        "\0".parent::class."\0".'form_attach_form' => [parent::class, 'form_attach_form', null],
        "\0".parent::class."\0".'form_link' => [parent::class, 'form_link', null],
        "\0".parent::class."\0".'form_reform' => [parent::class, 'form_reform', null],
        "\0".parent::class."\0".'form_task' => [parent::class, 'form_task', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'justification_form' => [parent::class, 'justification_form', null],
        "\0".parent::class."\0".'open' => [parent::class, 'open', null],
        "\0".parent::class."\0".'parentform_id' => [parent::class, 'parentform_id', null],
        "\0".parent::class."\0".'remark' => [parent::class, 'remark', null],
        "\0".parent::class."\0".'series' => [parent::class, 'series', null],
        "\0".parent::class."\0".'store_id' => [parent::class, 'store_id', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'type_id' => [parent::class, 'type_id', null],
        "\0".parent::class."\0".'version' => [parent::class, 'version', null],
        'chance' => [parent::class, 'chance', null],
        'close' => [parent::class, 'close', null],
        'connection_form' => [parent::class, 'connection_form', null],
        'created_by' => [parent::class, 'created_by', null],
        'date_created' => [parent::class, 'date_created', null],
        'date_effective' => [parent::class, 'date_effective', null],
        'form_attach_form' => [parent::class, 'form_attach_form', null],
        'form_link' => [parent::class, 'form_link', null],
        'form_reform' => [parent::class, 'form_reform', null],
        'form_task' => [parent::class, 'form_task', null],
        'id' => [parent::class, 'id', null],
        'justification_form' => [parent::class, 'justification_form', null],
        'open' => [parent::class, 'open', null],
        'parentform_id' => [parent::class, 'parentform_id', null],
        'remark' => [parent::class, 'remark', null],
        'series' => [parent::class, 'series', null],
        'store_id' => [parent::class, 'store_id', null],
        'title' => [parent::class, 'title', null],
        'type_id' => [parent::class, 'type_id', null],
        'version' => [parent::class, 'version', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
