<?php

namespace DoctrineProxies\__CG__\configuration_process;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class platform extends \configuration_process\platform implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'icon' => [parent::class, 'icon', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'path_id' => [parent::class, 'path_id', null],
        "\0".parent::class."\0".'platform_link' => [parent::class, 'platform_link', null],
        "\0".parent::class."\0".'user_type_platform' => [parent::class, 'user_type_platform', null],
        'description' => [parent::class, 'description', null],
        'icon' => [parent::class, 'icon', null],
        'id' => [parent::class, 'id', null],
        'path_id' => [parent::class, 'path_id', null],
        'platform_link' => [parent::class, 'platform_link', null],
        'user_type_platform' => [parent::class, 'user_type_platform', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
