<?php

namespace DoctrineProxies\__CG__\MainDb\Configuration;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class open_play extends \MainDb\Configuration\open_play implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'allow_one_person_to_book' => [parent::class, 'allow_one_person_to_book', null],
        "\0".parent::class."\0".'custom_rate' => [parent::class, 'custom_rate', null],
        "\0".parent::class."\0".'default_rate_id' => [parent::class, 'default_rate_id', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'set_rates' => [parent::class, 'set_rates', null],
        'allow_one_person_to_book' => [parent::class, 'allow_one_person_to_book', null],
        'custom_rate' => [parent::class, 'custom_rate', null],
        'default_rate_id' => [parent::class, 'default_rate_id', null],
        'id' => [parent::class, 'id', null],
        'set_rates' => [parent::class, 'set_rates', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
