<?php

namespace DoctrineProxies\__CG__\MainDb\Configuration;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class user extends \MainDb\Configuration\user implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'first_name' => [parent::class, 'first_name', null],
        "\0".parent::class."\0".'form_link' => [parent::class, 'form_link', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'last_name' => [parent::class, 'last_name', null],
        "\0".parent::class."\0".'member' => [parent::class, 'member', null],
        "\0".parent::class."\0".'mobile' => [parent::class, 'mobile', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'position_id' => [parent::class, 'position_id', null],
        "\0".parent::class."\0".'update' => [parent::class, 'update', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'wallet' => [parent::class, 'wallet', null],
        'email' => [parent::class, 'email', null],
        'first_name' => [parent::class, 'first_name', null],
        'form_link' => [parent::class, 'form_link', null],
        'id' => [parent::class, 'id', null],
        'last_name' => [parent::class, 'last_name', null],
        'member' => [parent::class, 'member', null],
        'mobile' => [parent::class, 'mobile', null],
        'password' => [parent::class, 'password', null],
        'position_id' => [parent::class, 'position_id', null],
        'update' => [parent::class, 'update', null],
        'user' => [parent::class, 'user', null],
        'wallet' => [parent::class, 'wallet', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
