<?php

namespace DoctrineProxies\__CG__\MainDb\Configuration;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class membership extends \MainDb\Configuration\membership implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'accept_lifetime_membership' => [parent::class, 'accept_lifetime_membership', null],
        "\0".parent::class."\0".'allow_non_dues_paying_membership' => [parent::class, 'allow_non_dues_paying_membership', null],
        "\0".parent::class."\0".'category_of_non_due_paying_member' => [parent::class, 'category_of_non_due_paying_member', null],
        "\0".parent::class."\0".'collect_membership_end_term' => [parent::class, 'collect_membership_end_term', null],
        "\0".parent::class."\0".'collect_membership_first_use' => [parent::class, 'collect_membership_first_use', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'member' => [parent::class, 'member', null],
        "\0".parent::class."\0".'membership_fee' => [parent::class, 'membership_fee', null],
        "\0".parent::class."\0".'only_member' => [parent::class, 'only_member', null],
        'accept_lifetime_membership' => [parent::class, 'accept_lifetime_membership', null],
        'allow_non_dues_paying_membership' => [parent::class, 'allow_non_dues_paying_membership', null],
        'category_of_non_due_paying_member' => [parent::class, 'category_of_non_due_paying_member', null],
        'collect_membership_end_term' => [parent::class, 'collect_membership_end_term', null],
        'collect_membership_first_use' => [parent::class, 'collect_membership_first_use', null],
        'id' => [parent::class, 'id', null],
        'member' => [parent::class, 'member', null],
        'membership_fee' => [parent::class, 'membership_fee', null],
        'only_member' => [parent::class, 'only_member', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
