<?php

namespace DoctrineProxies\__CG__\process;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class user extends \process\user implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'user_form_connection' => [parent::class, 'user_form_connection', null],
        "\0".parent::class."\0".'user_form_editor' => [parent::class, 'user_form_editor', null],
        "\0".parent::class."\0".'user_form_generator' => [parent::class, 'user_form_generator', null],
        "\0".parent::class."\0".'user_form_validation' => [parent::class, 'user_form_validation', null],
        "\0".parent::class."\0".'user_itinerary_connection' => [parent::class, 'user_itinerary_connection', null],
        "\0".parent::class."\0".'user_itinerary_generator' => [parent::class, 'user_itinerary_generator', null],
        "\0".parent::class."\0".'user_itinerary_validation' => [parent::class, 'user_itinerary_validation', null],
        "\0".parent::class."\0".'user_notification' => [parent::class, 'user_notification', null],
        'id' => [parent::class, 'id', null],
        'user_form_connection' => [parent::class, 'user_form_connection', null],
        'user_form_editor' => [parent::class, 'user_form_editor', null],
        'user_form_generator' => [parent::class, 'user_form_generator', null],
        'user_form_validation' => [parent::class, 'user_form_validation', null],
        'user_itinerary_connection' => [parent::class, 'user_itinerary_connection', null],
        'user_itinerary_generator' => [parent::class, 'user_itinerary_generator', null],
        'user_itinerary_validation' => [parent::class, 'user_itinerary_validation', null],
        'user_notification' => [parent::class, 'user_notification', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
