<?php

namespace DoctrineProxies\__CG__\configuration;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class user extends \configuration\user implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activate' => [parent::class, 'activate', null],
        "\0".parent::class."\0".'bidirectional' => [parent::class, 'bidirectional', null],
        "\0".parent::class."\0".'change_password' => [parent::class, 'change_password', null],
        "\0".parent::class."\0".'database_name' => [parent::class, 'database_name', null],
        "\0".parent::class."\0".'distance' => [parent::class, 'distance', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'employee_number' => [parent::class, 'employee_number', null],
        "\0".parent::class."\0".'first_name' => [parent::class, 'first_name', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'last_name' => [parent::class, 'last_name', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'middle_name' => [parent::class, 'middle_name', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'path_id' => [parent::class, 'path_id', null],
        "\0".parent::class."\0".'picture' => [parent::class, 'picture', null],
        "\0".parent::class."\0".'store_id' => [parent::class, 'store_id', null],
        "\0".parent::class."\0".'time_location' => [parent::class, 'time_location', null],
        "\0".parent::class."\0".'type_id' => [parent::class, 'type_id', null],
        "\0".parent::class."\0".'user_assign_user' => [parent::class, 'user_assign_user', null],
        "\0".parent::class."\0".'user_category' => [parent::class, 'user_category', null],
        "\0".parent::class."\0".'user_store' => [parent::class, 'user_store', null],
        "\0".parent::class."\0".'user_user' => [parent::class, 'user_user', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'activate' => [parent::class, 'activate', null],
        'bidirectional' => [parent::class, 'bidirectional', null],
        'change_password' => [parent::class, 'change_password', null],
        'database_name' => [parent::class, 'database_name', null],
        'distance' => [parent::class, 'distance', null],
        'email' => [parent::class, 'email', null],
        'employee_number' => [parent::class, 'employee_number', null],
        'first_name' => [parent::class, 'first_name', null],
        'id' => [parent::class, 'id', null],
        'last_name' => [parent::class, 'last_name', null],
        'location' => [parent::class, 'location', null],
        'middle_name' => [parent::class, 'middle_name', null],
        'password' => [parent::class, 'password', null],
        'path_id' => [parent::class, 'path_id', null],
        'picture' => [parent::class, 'picture', null],
        'store_id' => [parent::class, 'store_id', null],
        'time_location' => [parent::class, 'time_location', null],
        'type_id' => [parent::class, 'type_id', null],
        'user_assign_user' => [parent::class, 'user_assign_user', null],
        'user_category' => [parent::class, 'user_category', null],
        'user_store' => [parent::class, 'user_store', null],
        'user_user' => [parent::class, 'user_user', null],
        'username' => [parent::class, 'username', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
